title: My blog I guess
author: Graham.S 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
theme: minima

The website where i talk about me and my wierd hobbys such as, 
<ul>
  <li> Understanding a-wings </li>  
  <li> rock climbing </li>
  <li> lego stuff </li>
  <li> starwars </li>
  <li> 3d printing </li>
</ul>

# social links
twitter_username:none, don't have one # DO NOT include the @ character, or else the build will fail!
github_username:  RZ-1-A # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
